version: "3.9"

services:
  backend:
    build: ./server/app
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/app
      - sqlite_data:/app/data
    env_file:
      - ./server/app/.env

  frontend:
    build: ./client/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  sqlite_data:
